# Global settings cho toàn bộ ứng dụng
# File này sẽ được load cho tất cả environments

# Cấu hình ứng dụng chung
app:
  name: "Ruby on Rails Tutorial Sample App"
  version: "1.0.0"
  description: "Sample application for Rails Tutorial"

# Cấu hình i18n
i18n:
  default_locale: "en"
  available_locales: ["en", "vi"]
  fallback_locale: "en"

# Cấu hình pagination
pagination:
  default_per_page: 10
  max_per_page: 100

# Cấu hình pagy
pagy:
  page_10: 10

# Cấu hình micropost
micropost:
  max_content_length: 140
  allowed_image_types: ["jpg", "jpeg", "gif", "png"]
  allowed_mime_types: ["image/jpeg", "image/jpg", "image/gif", "image/png"]
  allowed_mime_types_string: "image/jpeg,image/gif,image/png"
  max_image_size: 5 # MB

# Cấu hình gravatar
gravatar:
  default_size: 80
  small_size: 50

# Cấu hình session
session:
  remember_me_value: "1"
  remember_token_expires: 2592000 # 30 days in seconds

# Cấu hình password reset
password_reset:
  expires_in: 2 # hours

# Cấu hình email
email:
  from_address: "noreply@railstutorial.org"
  support_address: "support@railstutorial.org"
  subjects:
    account_activation: "Account activation"
    password_reset: "Password reset"
    password_reset_confirmation: "Password successfully changed"
  delivery_methods:
    test: "test"
    smtp: "smtp"
    sendmail: "sendmail"

# Cấu hình alert classes
alert:
  success: "alert-success"
  error: "alert-danger"
  danger: "alert-danger"
  warning: "alert-warning"
  info: "alert-info"

# Cấu hình social links
social:
  twitter: "https://twitter.com/railstutorial"
  facebook: "https://facebook.com/railstutorial"
  github: "https://github.com/railstutorial"

# Cấu hình URLs
urls:
  tutorial: "https://www.railstutorial.org/"
  author: "https://www.michaelhartl.com/"
  contact: "https://www.railstutorial.org/contact"
  help: "http://www.railstutorial.org/help"
  book: "http://www.railstutorial.org/book"
  news: "https://news.railstutorial.org/"
  gravatar: "https://secure.gravatar.com/avatar/"
  gravatar_edit: "https://gravatar.com/emails"
  rails: "https://rubyonrails.org/"

# Cấu hình cache
cache:
  expires_in: 3600 # seconds (1 hour)
